{
  "formatVersion": "1.1",
  "component": {
    "group": "com.momosoftworks",
    "module": "kawa-forge-gradle",
    "version": "0.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "kawa-forge-gradle-0.3.1.jar",
          "url": "kawa-forge-gradle-0.3.1.jar",
          "size": 85763,
          "sha512": "b069fd7fd20f48d50d8413cae8f96d6ca426af0c6834857c4b0d7f8d7a8c6edd1771c0567000cdd9c53b7428d7f68a97c93eb6dd939560bc64557f55e085fffe",
          "sha256": "d007b081042dbf2517529d7dacc74d499d93ba267b5dd6f741ae7a8ef92086c1",
          "sha1": "f97af070d51b9df4f05a1d509b026669d3618939",
          "md5": "e0849ab10524458499fb11843e169fff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "kawa-forge-gradle-0.3.1.jar",
          "url": "kawa-forge-gradle-0.3.1.jar",
          "size": 85763,
          "sha512": "b069fd7fd20f48d50d8413cae8f96d6ca426af0c6834857c4b0d7f8d7a8c6edd1771c0567000cdd9c53b7428d7f68a97c93eb6dd939560bc64557f55e085fffe",
          "sha256": "d007b081042dbf2517529d7dacc74d499d93ba267b5dd6f741ae7a8ef92086c1",
          "sha1": "f97af070d51b9df4f05a1d509b026669d3618939",
          "md5": "e0849ab10524458499fb11843e169fff"
        }
      ]
    }
  ]
}
