package com.momosoftworks.kawaforge.mixin;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.objectweb.asm.AnnotationVisitor;
import org.objectweb.asm.ClassReader;
import org.objectweb.asm.ClassVisitor;
import org.objectweb.asm.Opcodes;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

/**
 * Verifies that the KawaCompileTask's flow (compile DSL module first, 
 * then compile consumers with DSL on classpath) correctly preserves 
 * the procedural macro's ability to emit carrier payloads.
 */
class DslModuleOrderingTest {

    private static final String CLASS_CARRIER = "Lcom/momosoftworks/kawaforge/mixin/KawaMixinMeta;";

    @TempDir
    Path tmp;

    @BeforeAll
    static void requireKawa() {
        KawaTestHarness.assumeAvailable();
    }

    @Test
    void dslCompiledFirstPreservesMacros() throws Exception {
        // 1. Compile the DSL module into a shared output directory.
        String dslSource = new String(
            Files.readAllBytes(Paths.get("src/main/resources/kawaforge/mixin.scm")),
            StandardCharsets.UTF_8);
        
        // Use a single workDir so both compile calls target the same "kawa-out".
        Path workDir = tmp.resolve("kawa-work");
        Files.createDirectories(workDir);
        
        // First call: Compile the DSL.
        Path dslClasses = KawaTestHarness.compile(workDir, "mixin.scm", dslSource,
            Collections.emptyList());

        // 2. Compile a consumer fixture that imports the DSL.
        String consumer = 
            "(import (kawaforge mixin))\n" +
            "(define-mixin OrderingProbe (target \"a.B\"))\n";
        
        // Pass the output of the first compilation (the DSL classes) on the classpath.
        // We also need the annotation classes for the macro's generated bytecode to be valid.
        Path annotationClasses = Paths.get(com.momosoftworks.kawaforge.mixin.KawaMixinMeta.class.getProtectionDomain().getCodeSource().getLocation().toURI());
        Path out = KawaTestHarness.compile(workDir, "consumer.scm", consumer,
            Arrays.asList(annotationClasses, dslClasses));

        // 3. Assert the compiled OrderingProbe.class carries the carrier.
        byte[] classBytes = Files.readAllBytes(out.resolve("OrderingProbe.class"));
        final String[] payload = new String[1];
        
        new ClassReader(classBytes).accept(new ClassVisitor(Opcodes.ASM9) {
            @Override
            public AnnotationVisitor visitAnnotation(String desc, boolean visible) {
                if (CLASS_CARRIER.equals(desc)) {
                    return new AnnotationVisitor(Opcodes.ASM9) {
                        @Override
                        public void visit(String name, Object value) {
                            if ("value".equals(name)) payload[0] = (String) value;
                        }
                    };
                }
                return null;
            }
        }, 0);

        assertNotNull(payload[0], "class must carry KawaMixinMeta");
        assertEquals(
            "(@ Mixin (targets \"a.B\"))",
            payload[0]);
    }
}
