{
  "formatVersion": "1.1",
  "component": {
    "group": "com.momosoftworks",
    "module": "kawa-forge-gradle",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "kawa-forge-gradle-0.1.0.jar",
          "url": "kawa-forge-gradle-0.1.0.jar",
          "size": 23895,
          "sha512": "0b1d9fe48df387f45176a309c01d85f861ec14718248c13de2fce6560d001a4502f33203f398e56f3f3fbeeafda24f499a3b78d98d667804f26ce3b2a6a35364",
          "sha256": "967fa3436585d918678818d03bf7d5c4361e7d111020a29cc52491f49a53337b",
          "sha1": "414eabc11b31764bf1112e3279c3f5f59bfea48c",
          "md5": "d5b9f3d7f6dee0ebf4cc88547121c377"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kawa-forge-gradle-0.1.0.jar",
          "url": "kawa-forge-gradle-0.1.0.jar",
          "size": 23895,
          "sha512": "0b1d9fe48df387f45176a309c01d85f861ec14718248c13de2fce6560d001a4502f33203f398e56f3f3fbeeafda24f499a3b78d98d667804f26ce3b2a6a35364",
          "sha256": "967fa3436585d918678818d03bf7d5c4361e7d111020a29cc52491f49a53337b",
          "sha1": "414eabc11b31764bf1112e3279c3f5f59bfea48c",
          "md5": "d5b9f3d7f6dee0ebf4cc88547121c377"
        }
      ]
    }
  ]
}
