{
  "formatVersion": "1.1",
  "component": {
    "group": "com.momosoftworks",
    "module": "kawa-forge-gradle",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "kawa-forge-gradle-0.1.0.jar",
          "url": "kawa-forge-gradle-0.1.0.jar",
          "size": 23913,
          "sha512": "408b93fbdf1d7ca34286b12325a956766ddceb3f3da17e32636a8cf10568fd970dc526590b0628efee940cc8379b5463c5380782be9bc0e76b0d8c74f0a2641f",
          "sha256": "831aa8aa6ad4f145b5614b1184f8fb94d81e6b2b6cf2e63ac1099e6f824cd220",
          "sha1": "36ad98ee068b31a22b51b927f81ca72af2ea0206",
          "md5": "6db5ac983bc04bef97b96d2c115a0d91"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kawa-forge-gradle-0.1.0.jar",
          "url": "kawa-forge-gradle-0.1.0.jar",
          "size": 23913,
          "sha512": "408b93fbdf1d7ca34286b12325a956766ddceb3f3da17e32636a8cf10568fd970dc526590b0628efee940cc8379b5463c5380782be9bc0e76b0d8c74f0a2641f",
          "sha256": "831aa8aa6ad4f145b5614b1184f8fb94d81e6b2b6cf2e63ac1099e6f824cd220",
          "sha1": "36ad98ee068b31a22b51b927f81ca72af2ea0206",
          "md5": "6db5ac983bc04bef97b96d2c115a0d91"
        }
      ]
    }
  ]
}
