{
  "formatVersion": "1.1",
  "component": {
    "group": "com.momosoftworks",
    "module": "kawa-forge-gradle",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "kawa-forge-gradle-0.1.0.jar",
          "url": "kawa-forge-gradle-0.1.0.jar",
          "size": 23049,
          "sha512": "e57fff6cfbb289539a033fd6f3996e30794e5a5f0ec748efcee4d1fc05db1b9aa262da03858c3c47d348495f12c8768ba5db696a19b2fc9bb84e3d01ef0b79df",
          "sha256": "634a4ec430eeafaf6f4008ecc92e200ab1e375a286c0907bd9e8df94a941fbf6",
          "sha1": "d4723df2e60224bd5eb9e0691c2fc05269f554de",
          "md5": "bcd296f009e9a353dc6fa58276910876"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kawa-forge-gradle-0.1.0.jar",
          "url": "kawa-forge-gradle-0.1.0.jar",
          "size": 23049,
          "sha512": "e57fff6cfbb289539a033fd6f3996e30794e5a5f0ec748efcee4d1fc05db1b9aa262da03858c3c47d348495f12c8768ba5db696a19b2fc9bb84e3d01ef0b79df",
          "sha256": "634a4ec430eeafaf6f4008ecc92e200ab1e375a286c0907bd9e8df94a941fbf6",
          "sha1": "d4723df2e60224bd5eb9e0691c2fc05269f554de",
          "md5": "bcd296f009e9a353dc6fa58276910876"
        }
      ]
    }
  ]
}
