{
  "formatVersion": "1.1",
  "component": {
    "group": "com.momosoftworks",
    "module": "kawa-forge-gradle",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "kawa-forge-gradle-0.1.0.jar",
          "url": "kawa-forge-gradle-0.1.0.jar",
          "size": 23018,
          "sha512": "a66e8b4438493b68eb82f3cf9af79d96f5e158a035380532cb8883931b60134e4dcb8924397203a0b773ed22638a23c70a6a8cb19c60cd6068246d93688371b0",
          "sha256": "aa4b38056cf9752618a40fb8cf015f91eaf317b3e010751e4e06a4569f128f59",
          "sha1": "575834be2a9cfacfb2e6852e06726db98ce6ced4",
          "md5": "6e0d1b5d69c3ebf97b901dc60a0a4852"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kawa-forge-gradle-0.1.0.jar",
          "url": "kawa-forge-gradle-0.1.0.jar",
          "size": 23018,
          "sha512": "a66e8b4438493b68eb82f3cf9af79d96f5e158a035380532cb8883931b60134e4dcb8924397203a0b773ed22638a23c70a6a8cb19c60cd6068246d93688371b0",
          "sha256": "aa4b38056cf9752618a40fb8cf015f91eaf317b3e010751e4e06a4569f128f59",
          "sha1": "575834be2a9cfacfb2e6852e06726db98ce6ced4",
          "md5": "6e0d1b5d69c3ebf97b901dc60a0a4852"
        }
      ]
    }
  ]
}
